# This is a basic workflow to help you get started with Actions

name: Sync to Gitee

# Controls when the workflow will run
on:
  push:
    branches:
      - main  # 设置为你的默认分支

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Sync to Gitee
      env:
        GITEE_REPO: gitee.com/chenyingzi/FluentPython2ndCN.git
      run: |
        
        # 克隆 Gitee 仓库
        git clone --bare $GITEE_REPO gitee-repo
        cd gitee-repo
        
        # 添加GitHub仓库作为远程上游
        git remote add upstream https://github.com/chenyz1984/FluentPython2ndCN.git
        
        # 同步代码
        git fetch upstream
        git push --mirror "https://${{ secrets.GITEE_TOKEN }}@$GITEE_REPO"
        
        # 删除临时文件夹
        cd ..
        rm -rf gitee-repo
